cmake_minimum_required(VERSION 3.24)

if(NOT DEFINED NEOCAD_ROOT_DIR OR NEOCAD_ROOT_DIR STREQUAL "")
	message(FATAL_ERROR "NEOCAD_ROOT_DIR is required.")
endif()

if(NOT DEFINED NEOCAD_WINDOWS_TARGET OR NEOCAD_WINDOWS_TARGET STREQUAL "")
	set(NEOCAD_WINDOWS_TARGET "x86_64-pc-windows-msvc")
endif()

if(NOT DEFINED NEOCAD_WINDOWS_PORTABLE_STAGE_DIR OR NEOCAD_WINDOWS_PORTABLE_STAGE_DIR STREQUAL "")
	set(NEOCAD_WINDOWS_PORTABLE_STAGE_DIR "${NEOCAD_ROOT_DIR}/build/windows/portable/NeoCAD-portable-x64")
endif()

if(NOT DEFINED NEOCAD_WINDOWS_PORTABLE_ZIP OR NEOCAD_WINDOWS_PORTABLE_ZIP STREQUAL "")
	set(NEOCAD_WINDOWS_PORTABLE_ZIP "${NEOCAD_ROOT_DIR}/build/windows/portable/NeoCAD-portable-x64.zip")
endif()

if(NOT DEFINED NEOCAD_WINDOWS_FIXED_RUNTIME_DIR)
	set(NEOCAD_WINDOWS_FIXED_RUNTIME_DIR "")
endif()

if(NOT DEFINED NEOCAD_REQUIRE_FIXED_RUNTIME)
	set(NEOCAD_REQUIRE_FIXED_RUNTIME OFF)
endif()

set(NEOCAD_WINDOWS_EXECUTABLE_SOURCE "${NEOCAD_ROOT_DIR}/src-tauri/target/${NEOCAD_WINDOWS_TARGET}/release/neocad.exe")
set(NEOCAD_WINDOWS_EXECUTABLE_SOURCE_ALT "${NEOCAD_ROOT_DIR}/src-tauri/target/${NEOCAD_WINDOWS_TARGET}/release/NeoCAD.exe")
set(NEOCAD_WINDOWS_EXECUTABLE_DESTINATION "${NEOCAD_WINDOWS_PORTABLE_STAGE_DIR}/NeoCAD.exe")
set(NEOCAD_WINDOWS_LAUNCHER_SOURCE "${NEOCAD_ROOT_DIR}/cmake/NeoCADPortableLauncher.cmd")
set(NEOCAD_WINDOWS_LAUNCHER_DESTINATION "${NEOCAD_WINDOWS_PORTABLE_STAGE_DIR}/NeoCAD-portable.cmd")
set(NEOCAD_WINDOWS_RUNTIME_DESTINATION "${NEOCAD_WINDOWS_PORTABLE_STAGE_DIR}/webview2-fixed-runtime")

if(NOT EXISTS "${NEOCAD_WINDOWS_EXECUTABLE_SOURCE}" AND EXISTS "${NEOCAD_WINDOWS_EXECUTABLE_SOURCE_ALT}")
	set(NEOCAD_WINDOWS_EXECUTABLE_SOURCE "${NEOCAD_WINDOWS_EXECUTABLE_SOURCE_ALT}")
endif()

if(NOT EXISTS "${NEOCAD_WINDOWS_EXECUTABLE_SOURCE}")
	message(FATAL_ERROR
		"Windows executable not found under src-tauri/target/${NEOCAD_WINDOWS_TARGET}/release/. Run the Windows portable build target first."
	)
endif()

set(NEOCAD_FIXED_RUNTIME_PRESENT OFF)

if(NOT "${NEOCAD_WINDOWS_FIXED_RUNTIME_DIR}" STREQUAL "")
	if(IS_DIRECTORY "${NEOCAD_WINDOWS_FIXED_RUNTIME_DIR}" AND EXISTS "${NEOCAD_WINDOWS_FIXED_RUNTIME_DIR}/msedgewebview2.exe")
		set(NEOCAD_FIXED_RUNTIME_PRESENT ON)
	elseif(NEOCAD_REQUIRE_FIXED_RUNTIME)
		message(FATAL_ERROR
			"Expected an extracted WebView2 Fixed Runtime directory at ${NEOCAD_WINDOWS_FIXED_RUNTIME_DIR} containing msedgewebview2.exe."
		)
	endif()
elseif(NEOCAD_REQUIRE_FIXED_RUNTIME)
	message(FATAL_ERROR
		"NEOCAD_WINDOWS_FIXED_RUNTIME_DIR is empty. Extract the WebView2 Fixed Runtime to .webview2/fixed-runtime-x64 or configure another directory before building the fixed-runtime portable package."
	)
endif()

file(REMOVE_RECURSE "${NEOCAD_WINDOWS_PORTABLE_STAGE_DIR}")
file(MAKE_DIRECTORY "${NEOCAD_WINDOWS_PORTABLE_STAGE_DIR}")
file(COPY_FILE "${NEOCAD_WINDOWS_EXECUTABLE_SOURCE}" "${NEOCAD_WINDOWS_EXECUTABLE_DESTINATION}")
file(COPY_FILE "${NEOCAD_WINDOWS_LAUNCHER_SOURCE}" "${NEOCAD_WINDOWS_LAUNCHER_DESTINATION}")

if(NEOCAD_FIXED_RUNTIME_PRESENT)
	file(COPY "${NEOCAD_WINDOWS_FIXED_RUNTIME_DIR}/" DESTINATION "${NEOCAD_WINDOWS_RUNTIME_DESTINATION}")
endif()

get_filename_component(NEOCAD_WINDOWS_PORTABLE_PARENT_DIR "${NEOCAD_WINDOWS_PORTABLE_STAGE_DIR}" DIRECTORY)
get_filename_component(NEOCAD_WINDOWS_PORTABLE_STAGE_NAME "${NEOCAD_WINDOWS_PORTABLE_STAGE_DIR}" NAME)
get_filename_component(NEOCAD_WINDOWS_PORTABLE_ZIP_DIR "${NEOCAD_WINDOWS_PORTABLE_ZIP}" DIRECTORY)

file(MAKE_DIRECTORY "${NEOCAD_WINDOWS_PORTABLE_PARENT_DIR}")
file(MAKE_DIRECTORY "${NEOCAD_WINDOWS_PORTABLE_ZIP_DIR}")

if(EXISTS "${NEOCAD_WINDOWS_PORTABLE_ZIP}")
	file(REMOVE "${NEOCAD_WINDOWS_PORTABLE_ZIP}")
endif()

execute_process(
	COMMAND "${CMAKE_COMMAND}" -E tar cf "${NEOCAD_WINDOWS_PORTABLE_ZIP}" --format=zip "${NEOCAD_WINDOWS_PORTABLE_STAGE_NAME}"
	WORKING_DIRECTORY "${NEOCAD_WINDOWS_PORTABLE_PARENT_DIR}"
	COMMAND_ECHO STDOUT
	RESULT_VARIABLE NEOCAD_WINDOWS_PORTABLE_ARCHIVE_RESULT
)

if(NOT NEOCAD_WINDOWS_PORTABLE_ARCHIVE_RESULT EQUAL 0)
	message(FATAL_ERROR
		"Failed to create portable archive: ${NEOCAD_WINDOWS_PORTABLE_ZIP}"
	)
endif()

if(NEOCAD_FIXED_RUNTIME_PRESENT)
	message(STATUS "Created Windows portable package with bundled Fixed WebView2 Runtime: ${NEOCAD_WINDOWS_PORTABLE_ZIP}")
else()
	message(WARNING
		"Created Windows portable package without a bundled Fixed WebView2 Runtime. NeoCAD will rely on a system WebView2 Runtime unless you extract one to ${NEOCAD_WINDOWS_FIXED_RUNTIME_DIR} and rebuild."
	)
endif()
